# Generated by Django 2.0.4 on 2018-04-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SwatchDeviceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deveui', models.CharField(max_length=16)),
                ('appeui', models.CharField(max_length=16)),
                ('power_yn', models.CharField(max_length=1)),
                ('last_location_time', models.DateTimeField()),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'swatch.t_swatch_device_info2',
            },
        ),
    ]
