# Generated by Django 2.0.4 on 2018-04-25 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swatchdeviceinfo',
            options={'managed': False},
        ),
    ]
